apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-eks-dev
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: platform-eks-dev
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'
