apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: game-2048
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/platform-eks-dev/2048
    repoURL: 'https://github.com/kaio6fellipe/argo'
    targetRevision: HEAD
    directory:
      recurse: true
  project: apps
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
