apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.4.8
    helm:
      releaseName: aws-load-balancer-controller
      version: v3
      parameters:
        - name: clusterName
          value: platform-eks-dev
        - name: region
          value: us-east-1
  ignoreDifferences:
    - group: "*"
      kind: "Deployment"
      jqPathExpressions:
         # Ignore differences for VPC ID that was passed via Terraform
        - .spec.template.spec.containers[].args[3]
    - group: "*"
      kind: "ServiceAccount"
      jsonPointers:
        # Ignore differences for IAM Role that is passed via
        # annotations to the Service Account
        - /metadata/annotations
    - group: "*"
      kind: "MutatingWebhookConfiguration"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: "*"
      kind: "ValidatingWebhookConfiguration"
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
    - group: "*"
      kind: "Secret"
      jsonPointers:
        - /data
  project: platform-eks-dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
