apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.11.1
    chart: cert-manager
    helm:
      values: |
        nameOverride: cert-manager
        fullnameOverride: cert-manager
        installCRDs: true
        serviceAccount:
          create: true
          name: "cert-manager"
        securityContext:
          fsGroup: 65534
  ignoreDifferences:
    - group: "*"
      kind: "ServiceAccount"
      jsonPointers:
        # Ignore differences for IAM Role that is passed
        # via annotations to the Service Account
        - /metadata/annotations
  project: ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
