apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: cluster-autoscaler
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.28.0
    helm:
      releaseName: cluster-autoscaler
      version: v3
      parameters:
        - name: autoDiscovery.clusterName
          value: platform-eks-dev
        - name: fullnameOverride
          value: cluster-autoscaler
        - name: rbac.serviceAccount.name
          value: cluster-autoscaler
        - name: replicaCount
          value: "2"
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - cluster-autoscaler
    - group: "*"
      kind: "ServiceAccount"
      jsonPointers:
        # Ignore differences for IAM Role that is passed
        # via annotations to the Service Account
        - /metadata/annotations
    - group: "*"
      kind: "Deployment"
      jqPathExpressions:
        # Ignore Region parameter released with Terraform
        - .spec.template.spec.containers[].env[0]
  project: platform-eks-dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
