apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.8.1
    helm:
      releaseName: external-secrets
      version: v3
      valueFiles:
      - external-secrets/values.yaml
  project: ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
