apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.8.1
      helm:
        releaseName: external-secrets
        version: v3
    - path: clusters/platform-eks-dev/external-secrets
      repoURL: 'https://github.com/kaio6fellipe/argo'
      targetRevision: HEAD
  ignoreDifferences:
    - group: "*"
      kind: "*"
      managedFieldsManagers:
        - external-secrets
    - group: "*"
      kind: "ServiceAccount"
      jsonPointers:
        # Ignore differences for IAM Role that is passed
        # via annotations to the Service Account
        - /metadata/annotations
  project: ops
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
