apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.8.1
    helm:
      releaseName: external-secrets
      version: v3
  ignoreDifferences:
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - external-secrets
  - group: "*"
    kind: "ServiceAccount"
    jsonPointers:
    - /metadata/annotations # Ignore differences for IAM Role that is passed via annotations to the Service Account
  project: ops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
