apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.12.2
    helm:
      releaseName: external-dns
      version: v3
  ignoreDifferences:
    - group: "*"
      kind: "ServiceAccount"
      jsonPointers:
        # Ignore differences for IAM Role that is passed
        # via annotations to the Service Account
        - /metadata/annotations
  project: ops
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
