apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-eks-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/platform-eks-dev
    repoURL: 'https://github.com/kaio6fellipe/argo'
    targetRevision: HEAD
    directory:
      recurse: true
  project: ops
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
