apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/platform-eks-dev/crossplane/infra
    repoURL: 'https://github.com/kaio6fellipe/argo'
    targetRevision: HEAD
  project: ops
  # syncPolicy:
  #   automated: {}
  #   syncOptions:
  #     - CreateNamespace=true
