---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret-grafana
  namespace: grafana
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: GF_DATABASE_PASSWORD
      remoteRef:
        key: aws-rds-password
    - secretKey: example-binary
      remoteRef:
        key: example-binary
    - secretKey: key-value-foo
      remoteRef:
        key: example-key-value
        property: foo
    - secretKey: key-value-bar
      remoteRef:
        key: example-key-value
        property: bar
