---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret-grafana
  namespace: grafana
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
  data:
    - secretKey: GF_DATABASE_PASSWORD
      remoteRef:
        key: grafana-secrets
        property: GF_DATABASE_PASSWORD
    - secretKey: GF_AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: grafana-secrets
        property: GF_AUTH_GITHUB_CLIENT_ID
    - secretKey: GF_AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: grafana-secrets
        property: GF_AUTH_GITHUB_CLIENT_SECRET
    - secretKey: GF_SECURITY_ADMIN_USER
      remoteRef:
        key: grafana-secrets
        property: GF_SECURITY_ADMIN_USER
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: grafana-secrets
        property: GF_SECURITY_ADMIN_PASSWORD
