---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret-grafana-agent-operator-logs
  namespace: grafana-agent-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: logs-secret
  data:
    - secretKey: username
      remoteRef:
        key: grafana-cloud
        property: GRAFANA_CLOUD_LOGSUSER
    - secretKey: password
      remoteRef:
        key: grafana-cloud
        property: GRAFANA_CLOUD_TOKEN
