kind: ConfigMap
metadata:
  name: grafana-agent-logs
  namespace: grafana-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
apiVersion: v1
data:
  agent.yaml: |
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: platform-eks-dev
      configs:
      - name: integrations
        remote_write:
        - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
          basic_auth:
            username: ${GRAFANA_CLOUD_METRICSUSER}
            password: ${GRAFANA_CLOUD_TOKEN}
    integrations:
      prometheus_remote_write:
      - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
        basic_auth:
          username: ${GRAFANA_CLOUD_METRICSUSER}
          password: ${GRAFANA_CLOUD_TOKEN}

    logs:
      configs:
      - name: integrations
        clients:
        - url: https://logs-prod-006.grafana.net/loki/api/v1/push
          basic_auth:
            username: ${GRAFANA_CLOUD_LOGSUSER}
            password: ${GRAFANA_CLOUD_TOKEN}
          external_labels:
            cluster: platform-eks-dev
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
        scrape_configs:
        - job_name: integrations/grafana-mimir-logs
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - cri: {}
          relabel_configs:
            - action: keep
              regex: mimir-distributed-.*
              source_labels:
                - __meta_kubernetes_pod_label_helm_sh_chart
            - source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: __host__
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_container_name
              target_label: job
            - action: replace # Replace the cluster label if it isn't present already
              regex: ''
              replacement: k8s-cluster
              separator: ''
              source_labels:
                - cluster
              target_label: cluster
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace # Necessary for slow queries dashboard
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: name
            - action: replace # Not actually necessary, here for consistency with metrics
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
        - job_name: integrations/kubernetes/pod-logs
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - docker: {}
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: __host__
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_name
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
