---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret-grafana-agent
  namespace: grafana-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: eks-secret-grafana-agent
  data:
    - secretKey: GRAFANA_CLOUD_METRICSUSER
      remoteRef:
        key: grafana-cloud
        property: GRAFANA_CLOUD_METRICSUSER
    - secretKey: GRAFANA_CLOUD_LOGSUSER
      remoteRef:
        key: grafana-cloud
        property: GRAFANA_CLOUD_LOGSUSER
    - secretKey: GRAFANA_CLOUD_TOKEN
      remoteRef:
        key: grafana-cloud
        property: GRAFANA_CLOUD_TOKEN
