apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
spec:
  destination:
    namespace: grafana-agent
    server: 'https://kubernetes.default.svc'
  source:
    chart: prometheus-node-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.17.3
    helm:
      releaseName: nodeexporter
      version: v3
  project: platform-eks-dev
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
