apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: grafana-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-agent
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
  - kind: ServiceAccount
    name: grafana-agent
    namespace: grafana-agent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: grafana-agent
  name: grafana-agent
  namespace: grafana-agent
spec:
  ports:
    - name: grafana-agent-http-metrics
      port: 80
      targetPort: 80
  selector:
    name: grafana-agent
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-agent
  namespace: grafana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-agent
  serviceName: grafana-agent
  template:
    metadata:
      labels:
        name: grafana-agent
    spec:
      containers:
        - args:
            - -config.expand-env=true
            - -config.file=/etc/agent/agent.yaml
            - -enable-features=integrations-next
            - -server.http.address=0.0.0.0:80
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: GRAFANA_CLOUD_METRICSUSER
              valueFrom:
                secretKeyRef:
                  name: eks-secret-grafana-agent
                  key: GRAFANA_CLOUD_METRICSUSER
            - name: GRAFANA_CLOUD_LOGSUSER
              valueFrom:
                secretKeyRef:
                  name: eks-secret-grafana-agent
                  key: GRAFANA_CLOUD_LOGSUSER
            - name: GRAFANA_CLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: eks-secret-grafana-agent
                  key: GRAFANA_CLOUD_TOKEN
          image: grafana/agent:v0.33.1
          imagePullPolicy: IfNotPresent
          name: grafana-agent
          ports:
            - containerPort: 80
              name: http-metrics
          volumeMounts:
            - mountPath: /var/lib/agent
              name: agent-wal
            - mountPath: /etc/agent
              name: grafana-agent
      serviceAccountName: grafana-agent
      volumes:
        - configMap:
            name: grafana-agent
          name: grafana-agent
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: agent-wal
        namespace: grafana-agent
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
