kind: ConfigMap
metadata:
  name: grafana-agent-traces
apiVersion: v1
data:
  agent.yaml: |
    server:
      log_level: debug
    integrations:
      agent:
        enabled: true
        relabel_configs:
          - action: replace
            source_labels:
              - agent_hostname
            target_label: instance
    metrics:
      wal_directory: /var/lib/agent/wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: platform-eks-dev
      configs:
        - name: default
          scrape_configs:
            - job_name: tempo_service_graph_metrics
              static_configs:
                - targets: ['127.0.0.1:12345']
          remote_write:
            - url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom
              basic_auth:
                username: ${GRAFANA_CLOUD_METRICSUSER}
                password: ${GRAFANA_CLOUD_TOKEN}
    traces:
      configs:
        - batch:
              send_batch_size: 1000
              timeout: 5s
          name: default
          service_graphs:
            enabled: true
          automatic_logging:
            backend: stdout
            roots: true
          receivers:
              jaeger:
                  protocols:
                      grpc: null
                      thrift_binary: null
                      thrift_compact: null
                      thrift_http: null
                  remote_sampling:
                      strategy_file: /etc/agent/strategies.json
                      tls:
                          insecure: true
              opencensus: null
              otlp:
                  protocols:
                      grpc: null
                      http: null
              zipkin: null
          remote_write:
            - basic_auth:
                  password: ${GRAFANA_CLOUD_TOKEN}
                  username: ${GRAFANA_CLOUD_TRACESUSER}
              endpoint: tempo-prod-04-prod-us-east-0.grafana.net:443
              retry_on_failure:
                  enabled: false
          scrape_configs:
            - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
              tls_config:
                  ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  insecure_skip_verify: false
  strategies.json: '{"default_strategy": {"param": 0.001, "type": "probabilistic"}}'
