---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: arn:aws:iam::023093918714:role/crossplane-dev
spec:
  podSecurityContext:
    fsGroup: 2000
  securityContext:
    runAsUser: 0
  args:
    - '--debug'
    - '--terraform-native-provider-path=""'
