apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  namespace: crossplane-system
spec:
  podSecurityContext:
    fsGroup: 2000
  # securityContext:
  #   runAsUser: 0
  args:
    - '--debug'