---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret-crossplane-aws-secret
  namespace: crossplane-system
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-secret
  data:
    - secretKey: creds
      remoteRef:
        key: crossplane-aws-secret-credentials
