---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret-crossplane-aws-secret
  namespace: crossplane-system
  argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-creds
  data:
    - secretKey: creds
      remoteRef:
        key: crossplane-aws-secret-credentials
