---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: IRSA
    # source: WebIdentity
    # webIdentity:
    #   roleARN: "arn:aws:iam::023093918714:role/crossplane-dev"
