apiVersion: v1
data:
  accounts.bot: apiKey, login
  accounts.bot.enabled: "true"
  policy.csv: |
    # Policy for Admin
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, accounts, *, *, allow

    # Policy for Developers Team
    p, role:dev-team, applications, sync, */*, allow
    p, role:dev-team, applications, get, */*, allow
    p, role:dev-team, applications, delete, */pod, allow
    p, role:dev-team, applications, action/*, */*, allow
    p, role:dev-team, repositories, get, *, allow
    p, role:dev-team, repositories, create, *, allow
    p, role:dev-team, repositories, update, *, allow

    g, DEVOPS, role:org-admin
    g, DEVS, role:dev-team
  policy.default: role:readonly
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
