---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
  name: argo-rollouts
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
      - rollouts/status
      - rollouts/finalizers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - argoproj.io
    resources:
      - analysisruns
      - analysisruns/finalizers
      - experiments
      - experiments/finalizers
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - analysistemplates
      - clusteranalysistemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
      - apps
    resources:
      - deployments
      - podtemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - networking.k8s.io
      - extensions
    resources:
      - ingresses
    verbs:
      - create
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
      - destinationrules
    verbs:
      - watch
      - get
      - update
      - patch
      - list
  - apiGroups:
      - split.smi-spec.io
    resources:
      - trafficsplits
    verbs:
      - create
      - watch
      - get
      - update
      - patch
  - apiGroups:
      - getambassador.io
      - x.getambassador.io
    resources:
      - mappings
      - ambassadormappings
    verbs:
      - create
      - watch
      - get
      - update
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups:
      - elbv2.k8s.aws
    resources:
      - targetgroupbindings
    verbs:
      - list
      - get
  - apiGroups:
      - appmesh.k8s.aws
    resources:
      - virtualservices
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - appmesh.k8s.aws
    resources:
      - virtualnodes
      - virtualrouters
    verbs:
      - watch
      - get
      - list
      - update
      - patch
  - apiGroups:
      - traefik.containo.us
    resources:
      - traefikservices
    verbs:
      - watch
      - get
      - update
  - apiGroups:
      - apisix.apache.org
    resources:
      - apisixroutes
    verbs:
      - watch
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: aggregate-cluster-role
    app.kubernetes.io/name: argo-rollouts-aggregate-to-admin
    app.kubernetes.io/part-of: argo-rollouts
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: argo-rollouts-aggregate-to-admin
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
      - rollouts/scale
      - rollouts/status
      - experiments
      - analysistemplates
      - clusteranalysistemplates
      - analysisruns
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: aggregate-cluster-role
    app.kubernetes.io/name: argo-rollouts-aggregate-to-edit
    app.kubernetes.io/part-of: argo-rollouts
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: argo-rollouts-aggregate-to-edit
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
      - rollouts/scale
      - rollouts/status
      - experiments
      - analysistemplates
      - clusteranalysistemplates
      - analysisruns
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: aggregate-cluster-role
    app.kubernetes.io/name: argo-rollouts-aggregate-to-view
    app.kubernetes.io/part-of: argo-rollouts
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: argo-rollouts-aggregate-to-view
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - rollouts
      - rollouts/scale
      - experiments
      - analysistemplates
      - clusteranalysistemplates
      - analysisruns
    verbs:
      - get
      - list
      - watch
