---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret-argo-rollouts
  namespace: argo-rollouts
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: argo-rollouts-notification-secret
  data:
    - secretKey: example-string
      remoteRef:
        key: example-string
    - secretKey: example-binary
      remoteRef:
        key: example-binary
    - secretKey: key-value-foo
      remoteRef:
        key: example-key-value
        property: foo
    - secretKey: key-value-bar
      remoteRef:
        key: example-key-value
        property: bar
