---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: example-crossplane-bucket
  annotations:
    crossplane.io/external-name: example-crossplane-bucket
  namespace: crossplane-system
spec:
  forProvider:
    acl: private
    locationConstraint: us-east-1
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: default