---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-example-bucket
  # labels:
  #   testing.upbound.io/example-name: s3-crossplane-example
  namespace: crossplane-system
spec:
  forProvider:
    region: us-east-1
    objectLockEnabled: true
    tags:
      Name: SampleBucket
  providerConfigRef:
    name: default
