---
apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-example-bucket
  labels:
    testing.upbound.io/example-name: s3
  annotations:
    crossplane.io/external-name: crossplane-example-bucket
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    region: us-east-1
    forceDestroy: true
    tags:
      Name: SampleBucket
  providerConfigRef:
    name: default