apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    meta.upbound.io/example-id: rds/v1beta1/instance
  labels:
    testing.upbound.io/example-name: crossplane-example-dbinstance
  name: crossplane-example-dbinstance
spec:
  forProvider:
    region: us-east-1
    allocatedStorage: 10
    dbName: ExampleDB
    engine: mysql
    engineVersion: "5.7"
    instanceClass: db.t3.micro
    parameterGroupName: default.mysql5.7
    passwordSecretRef:
      key: aws-rds-password
      name: crossplane-rds-password
      namespace: crossplane-system
    skipFinalSnapshot: true
    username: foo