---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-crossplane-rds-password
  namespace: crossplane-system
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: platform-eks-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: crossplane-rds-password
  data:
    - secretKey: aws-rds-password
      remoteRef:
        key: aws-rds-password
